from: kubernetes/gke/very-large

# Cloud-provider specific configuration.
provider:
    type: kubernetes

# The instance configuration for a standard instance type
available_node_types:
    worker.default:
        node_config:
            resources:
                # 512GB - 17GB
                memory: 486Gi
