# Cloud-provider specific configuration.
provider:
    type: kubernetes

    cloud_provider:
        type: aws

# The instance configuration for a standard instance type
available_node_types:
    head.default:
        node_config:
            resources:
                cpu: 16
                memory: 64Gi
            dataDisks:
              - name: data-disk-1
                storageClass: "gp2"
                diskSize: 100Gi
    worker.default:
        node_config:
            resources:
                cpu: 16
                memory: 64Gi
            dataDisks:
              - name: data-disk-1
                storageClass: "gp2"
                diskSize: 200Gi
              - name: data-disk-2
                storageClass: "gp2"
                diskSize: 200Gi
