# Custom commands that will be run on the head node after common setup.
head_setup_commands:
    - cloudtik runtime install kafka --head
    - cloudtik runtime configure kafka --head

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands:
    - cloudtik runtime install kafka
    - cloudtik runtime configure kafka

# Command to start on the head node. You don't need to change this.
head_start_commands:
    - cloudtik runtime services kafka stop --head
    - cloudtik runtime services kafka start --head

# Command to start on worker nodes. You don't need to change this.
worker_start_commands:
    - cloudtik runtime services kafka stop
    - cloudtik runtime services kafka start

# Command to start on the head node. You don't need to change this.
head_stop_commands:
    - cloudtik runtime services kafka stop --head

# Command to start on worker nodes. You don't need to change this.
worker_stop_commands:
    - cloudtik runtime services kafka stop
