# Custom commands that will be run on the head node after common setup.
head_setup_commands:
    - cloudtik-hdfs install --head
    - cloudtik-hdfs configure --head

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands:
    - cloudtik-hdfs install
    - cloudtik-hdfs configure --head_address=$CLOUDTIK_HEAD_IP

# Command to start on the head node. You don't need to change this.
head_start_commands:
    - cloudtik-hdfs stop-head
    - cloudtik-hdfs start-head

# Command to start on worker nodes. You don't need to change this.
worker_start_commands:
    - cloudtik-hdfs stop-worker
    - cloudtik-hdfs start-worker

# Command to start on the head node. You don't need to change this.
head_stop_commands:
    - cloudtik-hdfs stop-head

# Command to start on worker nodes. You don't need to change this.
worker_stop_commands:
    - cloudtik-hdfs stop-worker
